[versions]
activityCompose = "1.12.1"
agp = "8.13.2"
appcompat = "1.7.1"
circleimageview = "3.1.0"
constraintlayout = "2.2.1"
drawerlayout = "1.2.0"
glide = "5.0.5"
googleServices = "4.4.4"
firebaseBom = "34.7.0"
lottie = "6.7.1"
material = "1.14.0-alpha07"
navigationUi = "2.9.6"
navigationFragment = "2.9.6"
okhttp = "5.3.2"
gson = "2.13.2"
photoview = "2.2.0"
roundedimageview = "2.3.0"
shimmer = "0.5.0"
swiperefreshlayout = "1.2.0"
transition = "1.6.0"
kotlin = "2.2.21"
viewpager2 = "1.1.0"
volley = "1.2.1"
ktfmt = "0.25.0"
mmkv = "2.3.0"
coreKtx = "1.17.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }

constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }

navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }

drawerlayout = { group = "androidx.drawerlayout", name = "drawerlayout", version.ref = "drawerlayout" }

photoview = { group = "com.github.chrisbanes", name = "PhotoView", version.ref = "photoview" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }

shimmer = { group = "com.facebook.shimmer", name = "shimmer", version.ref = "shimmer" }

lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }

activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

transition = { group = "androidx.transition", name = "transition", version.ref = "transition" }
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }

roundedimageview = { group = "com.makeramen", name = "roundedimageview", version.ref = "roundedimageview" }

volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }

circleimageview = { group = "de.hdodenhof", name = "circleimageview", version.ref = "circleimageview" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-database = { group = "com.google.firebase", name = "firebase-database" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }

mmkv = { group = "com.tencent", name = "mmkv", version.ref = "mmkv" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
ktfmt-gradle = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }

[bundles]

firebase = ["firebase-auth",
    "firebase-database",
    "firebase-storage",
    "firebase-messaging"]